name: Submit a Testimonial
description: Share your pilgrimage experience for our website (reviewed before publishing)
title: "[Testimonial] "
labels: ["testimony"]
assignees: ["andercastellanos"]
body:
  - type: input
    id: name
    attributes:
      label: Your Name
      placeholder: e.g., Maria G.
    validations:
      required: true

  - type: input
    id: trip
    attributes:
      label: Trip / Destination
      placeholder: e.g., Medjugorje (May 2025)
    validations:
      required: true

  - type: textarea
    id: testimonial
    attributes:
      label: Your Testimonial
      description: Share highlights, moments of grace, logistics (guide/hotel/transport), etc.
    validations:
      required: true

  - type: textarea
    id: photo
    attributes:
      label: Photo (optional)
      description: Drag & drop or paste an image here to upload.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "By submitting, you agree that Sky Travel J & M may publish your testimonial and photo on our website."
